// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Frame.proto

package org.springframework.boot.netty.codec.proto;

public final class FrameOuterClass {
  private FrameOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Frame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Frame_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TextMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TextMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpeakMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpeakMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Frame.proto\"7\n\005Frame\022\014\n\004head\030\001 \001(\t\022\017\n\007" +
      "payload\030\002 \001(\014\022\017\n\007crcCode\030\003 \001(\t\"\033\n\013TextMe" +
      "ssage\022\014\n\004text\030\001 \001(\t\"(\n\014SpeakMessage\022\014\n\004t" +
      "ext\030\001 \001(\t\022\n\n\002id\030\002 \001(\tB.\n*org.springframe" +
      "work.boot.netty.codec.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Frame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Frame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Frame_descriptor,
        new java.lang.String[] { "Head", "Payload", "CrcCode", });
    internal_static_TextMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TextMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TextMessage_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_SpeakMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SpeakMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpeakMessage_descriptor,
        new java.lang.String[] { "Text", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
