// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Frame.proto

package org.springframework.boot.netty.codec.proto;

public interface SpeakMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SpeakMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * ID
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * ID
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
